name: Broken Security Test
on: [push]

jobs:
  hack_me:fvdf
    runs-on: ubunvdfvfdvtu-latevdfvdfst
    steps:
      - name: This will tfvdfvdfigger the scanneferferfvs
        # RULE BREAKER 1: Piping curl to bashvfv
        bfgdfvus.coriptdccxccsdsdsdcds.shdscsdc

        uiylui
        uikl
        u,
        ui,
        ui,
      - name: Leaking Secrets
        env:
          # RULE BREAKER 2: Hardcoded Secret
          STRIPE_KEY: "sk_live_51HvT.vcvdfvfdcv.."
          GEMINI_KEY: "SDLFGHKdcsddsdsSFHGKHdfvdfvdfvDSKFHGLHG"
        run: echo "I am leaking secrets"
