name: Intentional Failure
on: [push]
jobs:
  crash_job:
    runs-on: ubuntu-latest-0009
    steps:
      - name: Run Python Script
        run: python -c "import non_existentBVCFG_module"
        dfg fd
        f
        fgdJH GHJVGYHUV H
        bfgb
        dfgb
        fgb
        fgbfgbfg
